// Re-export Lucide React icons with consistent naming
export {
  Sparkles as SparklesIcon,
  User as UserIcon,
  ArrowUp as UpvoteIcon,
  MessageCircle as CommentIcon,
  Send as PaperAirplaneIcon,
  CheckCircle as CheckCircleIcon,
  ChevronLeft as ChevronLeftIcon,
  ShieldCheck as ShieldCheckIcon,
  ClipboardCheck as ClipboardDocumentCheckIcon,
  MessageSquare as ChatBubbleLeftRightIcon,
  Lightbulb as LightBulbIcon,
  BadgeCheck as CheckBadgeIcon,
  BookOpen as BookOpenIcon,
  Users as UsersIcon,
  Scissors as ScissorsIcon,
  Dumbbell as DumbbellIcon,
  Brain as BrainIcon,
  Heart as HeartIcon,
  Briefcase as BriefcaseIcon,
  Users as UserGroupIcon,
  Info as InformationCircleIcon,
  Clock as ClockIcon,
  Play as PlayIcon,
  Pause as PauseIcon,
  RotateCcw as ArrowPathIcon,
  Home,
  Target,
  TrendingUp,
  Calendar,
  Award,
  Settings,
  Menu,
  X,
  Plus,
  Minus,
  Star,
  Filter,
  Search,
  Bell,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  Download,
  Upload,
  Share,
  Copy,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Zap,
  Flame,
  Crown,
  Shield,
  Gem,
  TrendingUp as TrendingUpIcon,
  Calendar as CalendarIcon,
  RotateCcw as RefreshIcon,
  Trophy as TrophyIcon,
  Check as CheckIcon,
  Plus as PlusIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  AlertTriangle as AlertTriangleIcon
} from 'lucide-react';
